---
fixtures:
  repositories:
    apache: https://github.com/puppetlabs/puppetlabs-apache.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    epel: https://github.com/voxpupuli/puppet-epel.git
    python: https://github.com/voxpupuli/puppet-python.git
    selinux_core: https://github.com/puppetlabs/puppetlabs-selinux_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
